# Generated by Django 3.1.7 on 2021-03-03 06:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 3, 3, 6, 39, 57, 628102, tzinfo=utc))),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
